### ISSUE TITLE
Display the type of DNS used (adblocking, etc.)

### ISSUE THREAD

**Issue by ruihildt** [mullvad/browser-extension#100]
As a userm if I'm using Mullvad, I want to know if I am using Mullvad DNS adblocking/tracking.

**Comment by ph00lt0** [comment]
Seems more like a feature for the app, not for this extension.

**Comment by ruihildt** [comment]
It seems the only way to get that information would be to create a bridge to the Mullvad VPN app, so out of scope for this webextension.
