### ISSUE TITLE
Recommend to use DoH if not using Mullvad.

### ISSUE THREAD

**Issue by ruihildt** [mullvad/browser-extension#11]
When an extension user is not using Mullvad, we could recommend to them to use DoH and explain how to set it.

It's important to explain, because as of now, simply setting it in the Firefox settings without going to the `about:config` in Firefox will not force Firefox to use DoH all the time.

Aslo, see #9

**Comment by ph00lt0** [comment]
You shouldn't be recommending people to turn of the VPN. Defeats the purpose.

**Comment by ruihildt** [comment]
> You shouldn't be recommending people to turn of the VPN. Defeats the purpose.

This is true, but not all Mullvad Privacy Companion users are Mullvad users.

This recommendation would be only shown when you are not using Mullvad VPN. If If you are using Mullvad, you will be recommended not to use DoH. (See #9)
