### ISSUE TITLE
Stop recommending Cookie Autodelete

### ISSUE THREAD

**Issue by ph00lt0** [mullvad/browser-extension#120]
Using Firefox in strict mode (you should be recommending this) already prevents cookies from being used in other websites.

Also everyone can enable "Disable cookies and site data when Firefox is closed". You can even make exemptions for this. 

Using more extensions does not make you more private, likely the opposite:
- https://ieeexplore.ieee.org/document/7958618
- https://www.usenix.org/conference/usenixsecurity17/technical-sessions/presentation/sanchez-rola
- https://ieeexplore.ieee.org/document/7855963

Additionally this creates a false sense of security / privacy. Most websites use more then just cookies as identifiers such as local storage. Just deleting the cookies does not help you. By recommending this you may give people the impression that deleting the cookies will make services not recognize them any longer.

**Comment by parcelcat** [comment]
I have to disagree with this. [Cookie AutoDelete does clean LocalStorage](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enable-localstorage-support) and other forms of persistent data. "Delete cookies and site data when Firefox is closed" is a good browser feature, but Cookie AutoDelete goes even further by automatically deleting cookies for a domain when there are no tabs with that domain open. This lets users reset their session for that domain without having to restart Firefox, which would disrupt other tabs and windows.

**Comment by ph00lt0** [comment]
@parcelcat I didn't know about the localstorage, but this add-on still does not help you at all. 
It's false sense of security. Your browser does not get sanitized correctly. That besides cookies in correct strict configurations having minimal impact on your privacy. If you use Firefox in strict mode it isolates cookies used on different domains, so that there is no way for them to track you. Isolation is really well implemented in Firefox, preventing cookies from being used across websites. (https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/)

Having extensions with custom behavior only make you stand out from other visitors. 

There is no point in clearing up cookies on the website you already visited in your current session, as it has many other ways to distinguish you from others. Starting a new session with correct browser sanitation could actually help here in most cases, but as said you do not need to do this for not being tracked across different sites.

**Comment by parcelcat** [comment]
> There is no point in clearing up cookies on the website you already visited in your current session, as it has many other ways to distinguish you from others. Starting a new session with correct browser sanitation could actually help here in most cases

Cookie AutoDelete can delete everything for the domain that would be cleared by starting a new session, including cache, IndexedDB, LocalStorage, plugin data, and service workers. There's no need to start a new session when the extension performs the equivalent.

**Comment by ph00lt0** [comment]
@parcelcat please do your research before making false statements. What you say is incorrect, your comments can harm the security and privacy of others who believe you. Cookie Auto Delete does not remove all data.

Confirmed by authors themselves here:
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1298 

Also the plugin does not work correctly with strict mode in Firefox which is very problematic. Leading to false sense of security as I mentioned before.
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/807

The browser will constantly change, making the add-on also unreliable if the above would be resolved. You should not rely on the add-on being updated, else you risk leakage with every update on Firefox's implementation without you being aware of it. 

This in my opinion shows that it is a really bad idea to rely on add-on software to do this, when the browser has correct implementation itself. Generally using more add-ons only increases fingerprintabilty and attack surface. If you can do something without an add-on, don't install one! It is really bad practice and terrible advise.

**Comment by parcelcat** [comment]
The first link you provided is a report concerning the "Cleanup for Discarded/Unloaded Tabs" feature, not for Cookie AutoDelete clearing data for closed tabs in general. Please check your own research before making accusations.

There is nothing preventing anyone from using "Disable cookies and site data when Firefox is closed" and Cookie AutoDelete together. This is the setup I have, along with first-party isolation and a custom Enhanced Tracking Protection setting. This way, I don't have to constantly start new sessions to clear data from websites I no longer have open.

**Comment by Maryse47** [comment]
> It's false sense of security

Cookie Auto Delete has nothing to do with _security_.

> Firefox in strict mode it isolates cookies used on different domains, so that there is no way for them to track you

It does nothing on the _same_ domain though.

I would replace CAD with some containers extension.
