### ISSUE TITLE
VPN function in the extension?

### ISSUE THREAD

**Issue by PeterDaveHello** [mullvad/browser-extension#151]
Hi there,

We know that the browser extension doesn't provide the VPN function yet, just to enhance the browsing experience while using your VPN, but as a VPN service provider, who now even has a browser, is it possible that you'd also consider to make the extension able to has VPN function in it? So that your users won't have to have a system-wide VPN connection, when they're just trying to bypass some geo-location limit on certain website, or for some other testing purpose usages.

Thank you!

**Comment by ruihildt** [comment]
Hi, 

Mullvad Browser or Mullvad Browser Extension won't provide a VPN function only for the browser.
Our security model requires to have a VPN running for the whole system.

If you use a VPN through the browser proxy, it becomes extremely easy to shoot yourself in the foot:
- you rely on your browser to not send traffic outside the proxy, which is hard to guarantee 100% of the time.
- it's extremely easy to click on a link (for example a magnet or a zoom link) that would start a third party connection without VPN, which could be used to identify you.

**Comment by MrChocolatine** [comment]
Thanks to this issue today I learned about the existence of Mullvad Browser: (even if it's very recent)
https://mullvad.net/en/blog/2023/4/3/mullvad-vpn-and-the-tor-project-team-up-to-release-the-mullvad-browser/

While I try to regularly visit your blog, I don't do it enough, and it happened a lots of time where I missed such important news. I am sure I am not the only one in this situation.

That's too bad, this kind of news should be more promoted.

**Comment by PeterDaveHello** [comment]
@ruihildt got your point, guess the request is for different purpose, just to unlock geolocation than fighting censorship, still thanks though!

**Comment by ruihildt** [comment]
> just to unlock geolocation than fighting censorship, still thanks though!

You can change servers in the app for that, or you can try to use the proxy feature to change your country location.
But our focus is mainly on privacy indeed.
