### ISSUE TITLE
Firefox extension broken since Mullvad VPN update to version 2023.4

### ISSUE THREAD

**Issue by BMWBig6** [mullvad/browser-extension#171]
Mullvad Privacy Companion browser extension for Firefox no longer works properly since the Mullvad VPN client was recently updated to Version 2023.4.  It doesn't seem to toggle connecting/disconnecting proxy server anymore, and Firefox can only browse the web if Mullvad VPN is disconnected if the extension is installed.  I am connecting to Mullvad OpenVPN servers in case that makes a difference.

**Comment by ruihildt** [comment]
We could expect browsing being impossible if proxy is set and Mullvad VPN is off. But this is apparently the opposite.
Moreover, it should always be possible to disable the proxy. 

Can you confirm which version of the extension you're using?

**Comment by BMWBig6** [comment]
Ah, it appears I am using a very outdated version.  I thought the extension would automatically update itself. 
Version 0.5.2
Last Updated October 9, 2021

I will update the extension manually.  Mullvad recommended switching to a WireGuard VPN server and Firefox works if I use that (vs. OpenVPN server).

**Comment by BMWBig6** [comment]
Ah, it appears I am using a very outdated version.  I thought the extension would automatically update itself. 
Version 0.5.2
Last Updated October 9, 2021

I will update the extension manually.  Mullvad recommended switching to a WireGuard VPN server and Firefox works if I use that (vs. OpenVPN server).

**Comment by ruihildt** [comment]
Auto-update was only implemented in 0.7.9, sorry for the bad experience.

The extension will detect when you set the proxy whether you're using openvpn or wireguard at the time you set it, but it won't be able to update when you change protocol on the app side.

**Comment by BMWBig6** [comment]
Got it, thank you!  I guess being an early adopter of the beta extension I shouldn't have assumed auto-update was already baked in.  Glad to hear it has since been incorporated. Thanks for your assistance!
