### ISSUE TITLE
Use Leta login method from Mullvad Browser

### ISSUE THREAD

**Issue by deadcombo** [mullvad/browser-extension#172]
Hello,

Apologies if this is not the extension's domain, does Leta have its own issue tracker?

Anyway, I use temporary containers (one per tab / domain) so using Leta as a search engine means I need to login every time.
However I noticed in the Mullvad Browser the login persists across sessions, that is, if I fully close the browser I don't need to login next start.
Would this be applicable to Firefox?

Thank you.

**Comment by ruihildt** [comment]
The autologin functionality is provided by the extension and will work with regular Firefox, but unfortunately not with containers or in private mode.

I'll have to research more to see if there's a way to work around the issue.

**Comment by deadcombo** [comment]
My workaround is to assign Leta its own container with the Mozilla Multi-Account Containers extension. The temporary container extension can exclude it and it works quite well so far.
Leta remains logged in until the cookie expires as usual and the results all spawn in their own container.

Thanks for the info, I had assumed the autologin was part of the Mullvad Browser. Thank you as well for your work on all these privacy tools. I appreciate it.

**Comment by ruihildt** [comment]
Leta is now accessible without login.
