### ISSUE TITLE
Leta automatic login fail when searching highlighted text

### ISSUE THREAD

**Issue by cakeroasted** [mullvad/browser-extension#181]
I am using Mullvad browser, which has this extension. Automatic login to Leta function pertains to this extension, as per https://github.com/mullvad/browser-extension/issues/153. I have login number in the extension already.
When I enter search term into address field and press enter, it auto logs in and searches just fine. 

However, when I highlight text, right click, and select 'Search Mullvad Leta for "highlighted text"':
Expected behaviour: I should auto log in to Leta and get search results for selected text
Actual behaviour:  I am required to login before I get search results

**Comment by ruihildt** [comment]
Leta is now accessible without login.
