### ISSUE TITLE
Toolbar icon should change to indicate VPN is on/which location

### ISSUE THREAD

**Issue by Victor239** [mullvad/browser-extension#188]
The unofficial Mullvad Proxy extension has a better UX because it changes colour to indicate that it's turned on, and lists the country code that you're connected to. This is better than this official extension's approach which doesn't show country code, and the toolbar icon doesn't change. The icon in the URL bar instead is not very noticeable. 

![image](https://github.com/mullvad/browser-extension/assets/12621257/58fd9b22-7c42-4235-9039-58a1be94feb0)

**Comment by ruihildt** [comment]
With https://github.com/mullvad/browser-extension/pull/175, a badge with the country 2-letters code is displayed when a proxy is being used.
