### ISSUE TITLE
Change default keyword for Firefox search engine

### ISSUE THREAD

**Issue by kema-dev** [mullvad/browser-extension#189]
Extension's manifest adds Leta as search engine, and sets the default keyword to <kbd>m</kbd>  as per this line.
https://github.com/mullvad/browser-extension/blob/ab7e708cfe5533328fec5a524ead8d382941cb13/src/manifest.ts#L59
However, I would like to use this keyword for another search engine.

Currently, the <kbd>m</kbd> shortcut is hard coded in the manifest and forced each time I restart my browser, thus I can't use it for another search engine.

Do you think that setting it to  `@mullvad`, `@leta` or whatever would be ok ? This would comply with Firefox's default search engines.

**Comment by ruihildt** [comment]
Changed it to `leta`. 

This will be part of the next minor release.
