### ISSUE TITLE
Any plans to make the extension available for Chromium Browser ?

### ISSUE THREAD

**Issue by drkhero** [mullvad/browser-extension#192]
Any plans to make the extension available for Chromium Browser ? I see Chrome is mentioned in the last update, but I don't see anywhere where we can donwload the extension for Chromium browsers.

With the new changes of having a proxy set per tab, Mullvad extension could be very interesting for Chromium browsers, considering it's the closest thing they'll ever get to Firefox containers.

**Comment by ruihildt** [comment]
It is not planned to adapt the Mullvad Browser Extension for chromium based browsers, as it's not a priority at the moment. This would require some work, as the proxy webextension API is different for chromium browsers.

We will reevaluate if necessary at some point in the future.

**Comment by trash-anger** [comment]
It could be interesting for brave users who generally use brave because they need a chromium compatibility. 🙂
