### ISSUE TITLE
Addon 0.90 Beta does not work with OpenVPN

### ISSUE THREAD

**Issue by strykenKN** [mullvad/browser-extension#193]
The update to version 0.90 beta just came in and since then only chaos with the browser! The browser no longer works in any way, you can no longer establish a connection. Mullvad is now forcing every user to switch to Wireguard if you want to use the addon, because the addon no longer works with OpenVPN!

Even with Wireguard you can no longer establish a connection and the browser works in a continuous loop to establish a page. 

Even if you disable the addon, the browser has immense difficulties to build pages afterwards. 

No matter how you use the addon, you can no longer establish a connection and the fact that you can supposedly only use it with Wireguard is clearly a step backwards and unusable. 

In the end, Mullvad made it absolutely worse and should have left it as it was before!

And the fact that it supposedly now also causes problems with Ublock Origin (you have to switch off a function so that it supposedly works properly), as Mullvad himself writes, is unacceptable in my eyes.

And for your information, as long as Wireguard is still saving my IP address during my session, I don't want to use it, because Wireguard is nowhere near the security of OpenVPN. And as long as this is not fixed, I will refuse to use Wireguard.

**Comment by MrChocolatine** [comment]
> And the fact that it supposedly now also causes problems with Ublock Origin (you have to switch off a function so that it supposedly works properly), as Mullvad himself writes, is unacceptable in my eyes.

Maybe because of what is explained in the BETA changelog:
https://github.com/mullvad/browser-extension/releases/tag/v0.9.0-firefox-beta

> If another extension is using the [dns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/dns) permission, this extension DNS requests might not be proxied. This is notably the case of uBlock Origin's [Uncloak canonical names](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names) setting.
> It is worth remembering DNS requests outside the proxy made by a third-party extension will not leak, because Mullvad's proxy only works inside of a Mullvad VPN tunnel. This is why DNS leaks are a very unlikely scenario.

**Comment by OhKayBet** [comment]
On the topic of the post I've similarly have had an issue with changing proxy location from the existing one pre-update causes the browser to just stop working (Mullvad browser). Was trying to test the new proxy by website feature and once I selected the new location connection stopped working and the list to change locations shows as empty, as well without the ability to disconnect from the proxy. Ive been hesitant to test on Firefox as I'm not trying to be left without browser functionality.

On the philosophical side, while I only use Wireguard and haven't tried OpenVPN, the decision to remove OpenVPN is pretty anti-consumer and does leave a sour taste. Decision should be left up to the end user as how they want things configured. They stated the desire to provide a more simplistic experience, but as I recall the old layout had everything you needed to see on one screen with a large button allowing to disconnect from the proxy. Moving to separate the proxy and status on separate tabs requires more user input and the removing of a disconnect button leaves much to be desired. I recognize the separate tabs is to not crowd up the status screen, but I would have preferred having just a change proxy button at the bottom allowing to set it for the browser or website and the proxy tab being used as a master configuration of all saved website proxy links. I feel this approach would have kept simplicity and added function for power users.

Conspiratorially, I can only see the reason Mullvad removing OpenVPN as an option would be trying to move away and depreciate their OpenVPN servers otherwise it wouldn't make sense as why they're making the decision for the end user.

**Comment by strykenKN** [comment]
> On the topic of the post I've similarly have had an issue with changing proxy location from the existing one pre-update causes the browser to just stop working (Mullvad browser). Was trying to test the new proxy by website feature and once I selected the new location connection stopped working and the list to change locations shows as empty, as well without the ability to disconnect from the proxy. Ive been hesitant to test on Firefox as I'm not trying to be left without browser functionality.
> 
> On the philosophical side, while I only use Wireguard and haven't tried OpenVPN, the decision to remove OpenVPN is pretty anti-consumer and does leave a sour taste. Decision should be left up to the end user as how they want things configured. They stated the desire to provide a more simplistic experience, but as I recall the old layout had everything you needed to see on one screen with a large button allowing to disconnect from the proxy. Moving to separate the proxy and status on separate tabs requires more user input and the removing of a disconnect button leaves much to be desired. I recognize the separate tabs is to not crowd up the status screen, but I would have preferred having just a change proxy button at the bottom allowing to set it for the browser or website and the proxy tab being used as a master configuration of all saved website proxy links. I feel this approach would have kept simplicity and added function for power users.
> 
> Conspiratorially, I can only see the reason Mullvad removing OpenVPN as an option would be trying to move away and depreciate their OpenVPN servers otherwise it wouldn't make sense as why they're making the decision for the end user.

That is precisely the problem. Mullvad forces the customer who pays to use the addon to use Wireguard. And as long as Wireguard is not as secure as OpenVPN and it is not, I will not use Wireguard! 


I find it impossible that the new beta has caused more problems and still does and OpenVPN users (who pay) are absolutely exempt. This is not on! Mullvad wants to "force" users to use Wireguard! 


Users who have received the update cannot know why websites are no longer opening. How could they!  They are simply introducing something that the user probably doesn't want and blocking OpenVPN users. What is Mullvad thinking?  What does Mullvad want to achieve with this? 


I never had such problems as yesterday after the update and I find it simply cheeky how Mullvad behaves and has not yet commented on it. I would recommend everyone to uninstall the addon until some things are clarified here and discussed with the paying user. Sorry, but I'm really pissed off and I'm really fed up now.  I spent an hour yesterday after the update trying to get pages to open properly again, troubleshooting etc. Because absolutely nothing worked after the update!

**Comment by MrChocolatine** [comment]
I can also confirm the latest version [v0.9.0-firefox-beta](https://github.com/mullvad/browser-extension/releases/tag/v0.9.0-firefox-beta) does not allow users to use OpenVPN.

From what I can see the change of preventing the use of OpenVPN was made here: (from #175 )
https://github.com/mullvad/browser-extension/commit/de538a706d69a631c22bac737ea02db547f7b9b8

Using the previous version [v0.8.5-firefox-beta](https://github.com/mullvad/browser-extension/releases/tag/v0.8.5-firefox-beta) still works with OpenVPN.

No mention at all of this disruptive change on the [changelog](https://github.com/mullvad/browser-extension/releases/tag/v0.9.0-firefox-beta) apart from:
> This is a major refactor of the way proxy works in the extension.
> Instead of a proxy config being used for the whole browser,

It looks like this major change should be highlighted as a breaking change, not as a simple refactor.

---

> Wireguard is nowhere near the security of OpenVPN
> ...
> And as long as Wireguard is not as secure as OpenVPN and it is not

Genuinely curious, so I can learn more, where/what does it say Wireguard is not as secure as OpenVPN?
I always thought WireGuard was stable enough to be considered as safe alternative to OpenVPN.

- https://mullvad.net/en/help/why-wireguard

**Comment by ruihildt** [comment]
> No matter how you use the addon, you can no longer establish a connection and the fact that you can supposedly only use it with Wireguard is clearly a step backwards and unusable.

Proxying through OpenVPN is not supported anymore. The reason for this change is that the proxy with OpenVPN is very limited in functionality as the proxy exit is the same as the OpenVPN server you're currently connected to.
If you need to proxy with OpenVPN, you can use the Firefox native proxy settings in `Menu` > `Settings` > `General` > `Network Settings` as before.

I have added this information to the changelog, I apologize for forgetting to add it there.

**Comment by ruihildt** [comment]
> Conspiratorially, I can only see the reason Mullvad removing OpenVPN as an option would be trying to move away and depreciate their OpenVPN servers otherwise it wouldn't make sense as why they're making the decision for the end user.

The reason why we removed OpenVPN support through the browser extension is mainly because the benefits you can get (selecting a different location per URL) is not possible with OpenVPN at all.
As I noted in the updated changelog, on the server side, the proxying over OpenVPN is still working as before through the Firefox settings directly.

**Comment by ruihildt** [comment]
To anyone reading this issue, if you are stuck and can't connect to internet, there two possible options.

### Option 1
This will delete your current proxy settings, and you will be connecting to the internet through you current system connection.

- go to `about:debugging#/runtime/this-firefox`
- scroll until `Mullvad Browser Extension` and click on `Inspect`
- the `Developer Tools` window opens
- click on the `Storage` tab
- on the left menu, click on `Extension Storage`
- under `Extension Storage`, another line expands starting with `moz-extension://...`
- right click on it
- click `Delete all`

### Option 2
Re-install the previous extension and disable auto-update.
This should continue to work for the foreseeable future (and obviously you be getting any update, including security updates).

- go to `about:addons`
- uninstall the current Mullvad Browser Extension
- click on the following link: https://github.com/mullvad/browser-extension/releases/download/v0.8.5-firefox-beta/mullvad-browser-extension-0.8.5.xpi
- the installation is triggered, accept it
- go back to  `about:addons`
- on the extensions list, click on `Mullvad Browser Extension`
- toggle `Allow automatic updates` to `Off`

**Comment by ruihildt** [comment]
> They stated the desire to provide a more simplistic experience, but as I recall the old layout had everything you needed to see on one screen with a large button allowing to disconnect from the proxy. Moving to separate the proxy and status on separate tabs requires more user input and the removing of a disconnect button leaves much to be desired. I recognize the separate tabs is to not crowd up the status screen, but I would have preferred having just a change proxy button at the bottom allowing to set it for the browser or website and the proxy tab being used as a master configuration of all saved website proxy links. I feel this approach would have kept simplicity and added function for power users.

@OhKayBet Would you mind opening another issue with this, so we can have a dedicated space to discuss whether there are ways to improve the UI without making it too confusing?

**Comment by ruihildt** [comment]
In the next version, the popup UI has been reworked and the proxy has been brought back to the main view.

Closing this is issue, as we will not bring back OpenVPN support to the extension.
