### ISSUE TITLE
Not all local addresses are excluded from proxying

### ISSUE THREAD

**Issue by ruihildt** [mullvad/browser-extension#196]
Local addresses should always be excluded from proxying, this is not currently handled correctly. 

> 
> The private/local address subnets are:
> 
> 10.0.0.0 - 10.255.255.255 (10/8 prefix)
> 172.16.0.0 - 172.31.255.255 (172.16/12 prefix)
> 192.168.0.0 - 192.168.255.255 (192.168/16 prefix)
> 
> As seen here:
> 
> https://www.rfc-editor.org/rfc/rfc1918
> 
> https://superuser.com/questions/905660/what-other-ip-addresses-can-should-i-use-for-my-home-network

See: https://www.reddit.com/r/mullvadvpn/comments/1b9b2pf/please_add_option_to_never_proxy_local_addresses/

**Comment by oskaralmlov** [comment]
I would add these on top of the ones in the:
* 127.0.0.0/8 
* 169.254.0.0/16 
* 224.0.0.0/4
* fc00::/7 
* fe80::/64 from fe80::/10 
* ff00::/8 

https://en.wikipedia.org/wiki/Reserved_IP_addresses
