### ISSUE TITLE
Using a company proxy no longer works

### ISSUE THREAD

**Issue by quietsy** [mullvad/browser-extension#199]
Using a company proxy for company resources no longer works due to the new implementation of proxies overriding the browser proxy settings.

A possible solution is to support adding a custom user-defined proxy to the list of mullvad proxies.

**Comment by ruihildt** [comment]
Could you tell me how you usually set up you company proxy in your browser?
I'd like to reproduce the behavior and do some testing before trying out your suggestion.

**Comment by quietsy** [comment]
> Could you tell me how you usually set up you company proxy in your browser? I'd like to reproduce the behavior and do some testing before trying out your suggestion.

Sure, we define it under Settings > General > Network Settings > Manual proxy configuration > SOCKS host + port + SOCKS v5 + Proxy DNS.
Pretty much the same as setting Mullvad socks proxies manually.

**Comment by ruihildt** [comment]
@quietsy If you exclude the website from proxying in the Mullvad Browser Extension (`Proxy` > `Never proxy`), then the connection should fall back to the proxy you set under `Settings`,

Can you tell me if you can observe this behavior as well?

**Comment by quietsy** [comment]
> @quietsy If you exclude the website from proxying in the Mullvad Browser Extension (`Proxy` > `Never proxy`), then the connection should fall back to the proxy you set under `Settings`,
> 
> Can you tell me if you can observe this behavior as well?

Works perfectly, turning on "Proxy for all websites" and then selecting "Never proxy" on a specific site makes that specific site fall back to the proxy under Settings.
Thanks for the help!
