### ISSUE TITLE
Proxy for all sites breaks Kee Browser Extension

### ISSUE THREAD

**Issue by VIEWVIEWVIEW** [mullvad/browser-extension#202]
[Kee](https://addons.mozilla.org/de/firefox/addon/keefox/) is a browser extension for Firefox. It allows the user to autofill passwords using the credentials from [KeePass 2 ](https://keepass.info/download.html)using an RPC which opens an RPC server on [localhost](https://github.com/kee-org/keepassrpc/blob/86a12b9bfedd0df8724992f0e05a36fa6a520ad5/KeePassRPC/KeePassRPCServer.cs#L33).

When installing the Mullvad Browser Extension and enabling the "Proxy for All Websites" feature, the Kee Browser Extension stops working **after a browser restart** and can't connect to the KeePass RPC any more. This behaviour only started recently and wasn't the case a few weeks ago before the default proxy was replaced be the "Proxy for All Websites"-switch.

## Repro
1.  Ensure KeePass and Kee extension are configured correctly and operational.
2. Install Mullvad Browser Extension.
3. Enable the "Proxy for All Websites" feature in the Mullvad extension settings 
4. Restart firefox.
5. Watch how the connection between Kee and KeePass doesn't work anymore.
6. It starts working again when disabling the "Proxy for All Websites" feature.

The only workaround is to disable the "Proxy for All Websites" switch, let Kee connect to KeePass, and then enable the "Proxy for All Websites" again.

As I said: this issue only appeared recently and didn't happen in the old versions of Mullvad's Browser Extension

## System Info
- Firefox 124.0 
- Windows 10 x64
- KeePass 2 2.55
- Kee 3.11.13 (Oct 18, 2023)
- Mullvad Browser Extension 0.9.0
- KeePassRPC 1.16.0

**Comment by ruihildt** [comment]
This is most probably because we're not excluding properly all localhost requests, see #196

**Comment by VIEWVIEWVIEW** [comment]
> This is most probably because we're not excluding properly all localhost requests, see #196

You mention in the reddit thread that you exclude ``localhost`` and ``127.0.0.1`` and ``::1``. However, the RPC serve is opened on ``127.0.0.1`` (it's actually a websocket server), therefore it is supposed to work, or?

**Comment by ruihildt** [comment]
I guess it should, but I don't know.

**Comment by VIEWVIEWVIEW** [comment]
> I guess it should, but I don't know.

Who could know, or what could a way towards fixing this look like? I really like this extension and it would be too sad to not having this fixed :(

**Comment by ruihildt** [comment]
I'll start by fixing #196.

In parallel, I recommend contacting the creator of this extension, as they probably know better what errors are showing up and what they mean.

**Comment by ruihildt** [comment]
@VIEWVIEWVIEW Can you check if it's fixed with the latest `0.9.3` release?

**Comment by VIEWVIEWVIEW** [comment]
> @VIEWVIEWVIEW Can you check if it's fixed with the latest `0.9.3` release?

It works now! Thank you many times for fixing it! :)
