### ISSUE TITLE
Links to unofficial website for uBlock Origin

### ISSUE THREAD

**Issue by squeak9** [mullvad/browser-extension#206]
Go to settings, scroll down, and you will find privacy recommendations for uBlock Origin with 'Learn More' link that leads to https://ublockorigin.com/.

The issue is that it's not the official website for uBlock Origin because there is no official website for it, as explained here: https://github.com/gorhill/uBlock/wiki/Why-don't-you-accept-donations%3F

It's not a bad site, just to be clear; it's actually pretty informative, and there are no weird ads or scams, just some minor self-promotion at the end. I think it exists to promote the add-on while preventing others from creating a shadier version of it.

Still, the add-on should probably just link to https://github.com/gorhill/uBlock to make it more transparent.

**Comment by MrChocolatine** [comment]
I agree, also see this URL: https://github.com/gorhill/uBlock/wiki/Unofficial-websites

Change proposed @ruihildt : #207

**Comment by squeak9** [comment]
This somehow didn't get fixed? Or it got added back in? 
![QHEpbwJu0C](https://github.com/user-attachments/assets/b5944e10-b01d-4a1d-b24e-e460360392d1)

**Comment by MrChocolatine** [comment]
> This somehow didn't get fixed? Or it got added back in? 

I reported (what I think is) the same issue but on Mullvad Browser and got this answer:

https://github.com/mullvad/browser-extension/issues/258#issuecomment-2483984634
> It's very likely this is because the local storage is not reset on update.

**Comment by squeak9** [comment]
Huh, weird. Yeah, i uninstalled (and deleted the left over data) and then reinstalled and its fixed.
Thanks for the info 👍
