### ISSUE TITLE
[Bug] Cannot resolve amzn.to name when connected to se-got-wg-001 server

### ISSUE THREAD

**Issue by ghost** [mullvad/browser-extension#225]
The following conditions prevent name resolution for amzn.to

- Mullvad VPN: hk-hkg-wg-302 -> jp-osa-wg-004 (Multihop)
- VPN Client: Mullvad App 2024.3
- OS: Arch Linux
- Browser: Firefox 127.0.2 archlinux-1.0

---
Could be a problem similar to mullvad/mullvadvpn-app#5706.

**Comment by ruihildt** [comment]
This is a network question not directly related to the extension.

Please contact support@mullvadvpn.net.
