### ISSUE TITLE
Per Tab Proxy is Obscure and Broken

### ISSUE THREAD

**Issue by issuant** [mullvad/browser-extension#226]
A comment on reddit just informed me that it is possible to set a proxy per tab. This was surprising information as it's not mentioned in any [official documents](https://mullvad.net/en/help/tag/mullvad-browser) at all and almost impossible to 'stumble on' with how the extension popup is designed.

I played around with it and the UX is not good at all. With how it is currently, it isn't so much a 'per tab' proxy as it is a 'per site' proxy. There are no options to actually pre-set a preferred location in the new tab until after fully loading a website, identifying you to the website across both locations. 

After setting it, I now cannot find a way to deactivate the 'per site' proxy. Only a notification that the website is proxied through a different location than the general browser and new buttons with no explanation that never go away, 'Never Proxy' and 'Turn Off DNS'. The per site proxy persists even with browser relaunches and the 'New Identity' button does nothing to help.

There is also no way to find out which sites may have a preexisting proxy configured so you simply have to wing it and be surprised when some website loads.

**Comment by ruihildt** [comment]
Here's my first try at addressing those issues. I would be grateful if any of you could give me some feedback.

[Screencast_20240814_174934.webm](https://github.com/user-attachments/assets/c2a8daf9-132d-4db8-a78a-57f6cef9d234)

**Comment by ruihildt** [comment]
It's now possible to add a proxy manually:
![image](https://github.com/user-attachments/assets/b5d745af-39ca-4add-8a36-f68c2ad677f7)

**Comment by ruihildt** [comment]
Fixed by https://github.com/mullvad/browser-extension/pull/243

**Comment by ruihildt** [comment]
Sorry missed it, here is the behavior:
- set a proxy for `domain.tld`
- load a website `domain.tld`
- in the current tab where the domain is being loaded, all requests emitted from that tab will be proxied through the same proxy

So yes, everything loaded through the specific domain will use the same proxy.

If you want to look at the code, here are the two relevant functions taking care of this logic:
- https://github.com/mullvad/browser-extension/blob/ab56f6f2815a1aa28e30006f1fd3253a1f4818d4/src/helpers/socksProxy.ts#L86
- https://github.com/mullvad/browser-extension/blob/ab56f6f2815a1aa28e30006f1fd3253a1f4818d4/src/helpers/socksProxy.ts#L52

**Comment by ruihildt** [comment]
I have edited my explanation for clarity:
> So yes, every request initiated from a domain (including third party domains) will use the same proxy.

So if `github.com` is set to proxy through Albania, then assets loaded from third party domains like `https://*.githubusercontent.com` will load through the same Albania proxy.

If you load in a new tab `https://*.githubusercontent.com`, it will follow the `all websites` proxy configuration.

**Comment by ruihildt** [comment]
While working on the sub-domain matching feature, I have noticed there's some `speculative` connection going outside of the proxy.

This is because their origin are inaccurate:
![image](https://github.com/user-attachments/assets/8455fe52-4e65-46ab-a295-f3895a6b7649)

In the next version of the extension, these speculative requests are simply blocked.

**Comment by ruihildt** [comment]
Yes that is correct.
