### ISSUE TITLE
Allow per-domain proxies to be configured with wildcards

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [mullvad/browser-extension#232]
For example, if I set up my connection to `*.example.com` to use `bg-sof-wg-101`, I want `maps.example.com`, `login.example.com`, and `payments.example.com` to use `bg-sof-wg-101` as well.

**Comment by ruihildt** [comment]
After thinking about it, the plan is to have a wildcard by default.
But if you manually enter a domain with subdomain, then the more specific (sub-domain), will take precedence.

Do you think that makes sense?

**Comment by ruihildt** [comment]
Wildcard is not yet supported. To give you an example, if you setup a proxy `ip.me`, it will not apply to `www.ip.me`.

Regarding the difficulty about finding the "never proxy" option, where would you expect it to appear?

**Comment by ruihildt** [comment]
I opened as separate issue (https://github.com/mullvad/browser-extension/issues/255) for your other feedback.
