### ISSUE TITLE
Stuck on Checking connection; cannot reach ipv6.am.i.mullvad.net

### ISSUE THREAD

**Issue by gen495** [mullvad/browser-extension#239]
Platform: macOS 14.7
Mullvad app: 2024.5 (2024-09-03)
Browsers: Firefox 130.1, Firefox Nightly 132.0a1
Extension versions: 0.8.5, also seems to apply to 0.9.0

There is a possible confounding issue with how my system firewall is configured.
The issue applies with Mullvad app ipv6 both on and off.

Issue description:
- clicking on the Mullvad extension icon gives this 
![image](https://github.com/user-attachments/assets/9811261e-d67a-4eab-9b0a-e3eec7e64a0e)

it takes ~30-40 seconds to show the currently connected ipv4 proxy, and 10s more to show that the DNS leak tests failed.
Looking at the extension in the network tab, from `about:debugging#/runtime/this-firefox` -> inspect, there's an issue connecting to ipv6.am.i.mullvad.net (NS_ERROR_NET_TIMEOUT)

![image](https://github.com/user-attachments/assets/e7fc3d02-04ae-4d5d-8042-82f6b5a00358)

- the same issues are present in the network monitor tab for  https://mullvad.net/en/check, showing no ability to check for DNS leaks (NS_BINDING_ABORTED)
- clicking on the Mullvad extension icon while not connected to the proxy gives the same waiting delay, but clicking it again shows the connection information okay. (the connection to the ipv6 subdomain fails with NS_ERROR_UNKNOWN_HOST almost immediately)
- when disconnected from the proxy, it seems (with a single test) that the DNS leak checks succeed.

I can't seem to reach ipv6.am.i.mullvad.net on my host system either.
Going into the browser proxy settings and disabling "Proxy DNS when using SOCKS v5" sometimes makes this work, but sometimes not. It may be worth noting that the SOCKS host IP is different across different browser instances. My host just uses 10.64.0.1.

This seemed to be working mostly fine (with some issues maybe) about a week ago; I'm not sure if updating the desktop app caused anything to break or work better.

The issue persisted:
- in my original browser profile, temporarily disabling extensions and enabling 0.8.5
- in some other completely fresh browser profiles, in both Firefox and Firefox nightly

I don't have more time to debug right now, sorry.

**Workaround**
My UX issue of having to wait 30+ seconds to change location can be resolved by blocking requests to the ipv6 URL in devtools

**Comment by deadcombo** [comment]
I am experiencing the same issue and additionally when the answer does come back, the displayed connected proxy server is incorrect.

The workaround of blocking the ipv6 domain in the dev tools fixes both issues. I have ipv6 disabled in both the Mullvad app and in the firefox about:config pref.

**Comment by deadcombo** [comment]
@gen495 see #197 TL;DR reinstall the extension.

To clarify, I experienced both the issues described here and #197 simultaneously, including Mullvad Extension being set as controlling proxy settings in about:preferences.

**Comment by MrChocolatine** [comment]
I am having the same issue, the extension stuck on `Checking connection`:
![image](https://github.com/user-attachments/assets/b1fc8059-13cc-4474-b5ba-569af15334a9)

I am using through Mullvad Browser, which means I have not changed the browser default configuration.

**Comment by gen495** [comment]
Summary:
Servers where I can't connect: seemingly any M247 servers; most xtom servers
Servers where I can connect:
- most 31173 servers
- some xtom servers (mostly just ee-tll-wg-001, 002, 003)
- some Blix servers

Patterns I noticed:
- if `mullvad status` shows an IPv6 address, it's likely that ipv6.am.i.mullvad.net will be reachable. (Does it send a request there?)
- nevertheless, `ping6 ipv6.am.i.mullvad.net` behaves inconsistently, either working with 0% packet loss or 100% (retrying when it fails, it seems okay)
- even on 31173 servers, `curl --connect-timeout 5  ipv6.mullvad.net` doesn't always connect. Sometimes it needs to be tried again. It's inconsistent.
- (in the extension network tools, I no longer have issues connecting to the DNS leak test servers)

Caveats:
- I'm connected via an entry node. It doesn't seem to make much difference, but I don't know if it could.
- I didn't test ping to the address more than twice for each server, and curl just once (twice if mullvad does it on connection). This might not be enough testing.
- Semi-automated testing was only done on the OS

Some functions I used for debugging:
`hostedby() { mullvad relay list | grep wg | grep $1 | awk '{print $1}' }`
`testMtr() { mullvad relay set location $1; mullvad status; sleep 5; mullvad status;  sudo mtr ipv6.am.i.mullvad.net; mullvad status; curl --connect-timeout 5 'https://ipv6.am.i.mullvad.net' }`

---
I seem to have issues with M247 servers from my OS:
`mullvad status; mullvad relay list | grep $(mullvad status | head -n 1 | cut -d' ' -f3)`
```
Connected to us-dal-wg-001 in Dallas, TX, USA via [redacted]
Your connection appears to be from: USA, Dallas, TX
		us-dal-wg-001 (146.70.211.66, 2001:ac8:9a:76::1f) - WireGuard, hosted by M247 (rented)
```

`curl -6 --connect-timeout 5 'https://ipv6.am.i.mullvad.net'`
curl: (28) Failed to connect to ipv6.am.i.mullvad.net port 443 after 5005 ms: Timeout was reached

`ping6 ipv6.am.i.mullvad.net` always has 100% packet loss.

From 31173 (mullvad-owned) servers, the curl usually resolves to an IP address, but sometimes the ping doesn't work and has to be run again. (There's no packet loss when it works, but 100% packet loss when it doesn't work)
When running `mullvad status`, the IPv6 address usually appears immediately.
```
Connected to dk-cph-wg-001 in Copenhagen, Denmark via [redacted]
Your connection appears to be from: Denmark, Copenhagen. IPv4: 45.129.56.136, IPv6: 2a03:1b20:8:f011::e02b
```

---
From the extension, it's less easy to see the ownership of servers.
It's possible to make a list with `mullvad relay list | grep wg | grep 31173` and just select those. The proxies I've tested from here seem to work fine.
`curl 'https://api.mullvad.net/network/v1-beta1/socks-proxies' | jq '.' > proxies.json` - mostly the same as the list of relays, except it adds a few (for me)

**Comment by gsture** [comment]
Came here to report the same issue. Can not connect to any proxy at the moment. "Connect first to Mullvad VPN (WireGuard) to use the proxy."

**Comment by ruihildt** [comment]
@gsture Investigating the issue. It seems I can actually connect, but there's an issue with IPV6 and our connection check.

Since the extension relies on the conncheck to double check everything is in order, then it looks like you're not connected to the proxy, even though you actually are.

**Comment by ruihildt** [comment]
Here's a list of known socks proxy location which won't be able to resolve IPV6:

```
- ca-yyc-wg-socks5-201
- ca-yyc-wg-socks5-202
- de-ber-wg-socks5-002
- de-ber-wg-socks5-003
- de-ber-wg-socks5-004
- de-ber-wg-socks5-005
- de-ber-wg-socks5-006
- de-ber-wg-socks5-007
- es-bcn-wg-socks5-101
- es-bcn-wg-socks5-102
- fi-hel-wg-socks5-001
- lv-rix-wg-socks5-001
- se-mma-wg-socks5-004
- se-sto-wg-socks5-001
- se-sto-wg-socks5-002
- se-sto-wg-socks5-003
- se-sto-wg-socks5-004
- se-sto-wg-socks5-005
- se-sto-wg-socks5-006
- se-sto-wg-socks5-007
- se-sto-wg-socks5-008
- se-sto-wg-socks5-009
- se-sto-wg-socks5-011
- se-sto-wg-socks5-012
- se-sto-wg-socks5-014
- th-bkk-wg-socks5-001
- us-chi-wg-socks5-301
- us-chi-wg-socks5-302
- us-chi-wg-socks5-303
- us-chi-wg-socks5-304
- us-chi-wg-socks5-305
- us-chi-wg-socks5-306
- us-chi-wg-socks5-307
- us-chi-wg-socks5-308
- us-qas-wg-socks5-101
- us-sea-wg-socks5-103
```

**Comment by gsture** [comment]
The thing i don't understand is that I have ipv6 disabled on my computer and my network so why does the addon still need to check for ipv6 connectivity?

**Comment by ruihildt** [comment]
Normally, our connection check will fail immediately if ipv6 is not available. I'm planning address this by making the ipv6 check non blocking for the popup.

**Comment by ruihildt** [comment]
> I'm planning address this by making the ipv6 check non blocking for the extension popup.

This is now implemented in the [latest release](https://github.com/mullvad/browser-extension/releases/tag/v0.9.3-firefox-beta).

I'll close this issue, if you still have problems, feel free to open a separate issue.
