### ISSUE TITLE
Leta unset as default search when not connected

### ISSUE THREAD

**Issue by deadcombo** [mullvad/browser-extension#241]
Hello,

In light of #239 I'm often dealing with the extension not detecting the Mullvad connection. It seems this reverts my default search to 'Google' (presumably by Firefox default). I set Leta as default via the about:preferences page, not through the extension.

I find this change undesirable. Even were I not connected to Mullvad I'd prefer to get the Leta error page than silently have my default engine changed. I inevitably only find out when I accidentally send a query to Google. I don't think it should automatically revert to anything.

Thanks.

**Comment by ruihildt** [comment]
The extension adds Leta as a search engine, so if you disable the extension, the search engine is removed and goes back to default.

This is not something I can change. I can offer you to manually add Leta to Firefox, so it will not depend on whether the extension is active or not.

**Comment by deadcombo** [comment]
At no point have I disabled the extension and I did add Leta to Firefox myself (started using it before the extension offered it). I re-installed it once to deal with #197, this changed nothing about leta (still has the keyword I set for it).

The extension stays on, is connected (per am.i.mullvad) despite sometimes failing the check (see #239). The default search engine gets set to Google every once in a while. Leta is not removed from either the default list or the shortcuts list. 
I simply have to go to about:preferences and choose Leta from the dropdown again. I've had to do this 5 times, coinciding with the period the extension failing the connection checks, thus I believe it to be related. 

Perhaps it could be a regression in Firefox instead? Looking through Bugzilla makes me think this is unlikely, the couple of related reports point to external software modifying the search preferences and this extension is the only software I run that does that.

**Comment by ruihildt** [comment]
Extensions are not able to change the search engine settings, outside adding statically on extension start a new search engine.

At this point the most likely is that you found a Firefox bug related to default search engine. (and could be related to an extension setting a search engine^^")

Can you confirm your OS and Firefox version?
