### ISSUE TITLE
What happened to proxy DNS Checkbox?

### ISSUE THREAD

**Issue by zs311521** [mullvad/browser-extension#257]
It used to be a checkbox so I could untick proxy DNS so I could use my own private DNS. Now that checkbox is completely gone and is nowhere to be found in settings!  Could someone please send a screenshot as it is literally not anywhere there.

**Comment by ruihildt** [comment]
You can customize the proxy DNS in the extension settings for specific websites.

![image](https://github.com/user-attachments/assets/1062dc15-c54b-4075-8932-a3de42833bc9)

I haven't implemented the checkbox for `All websites` proxy. If this is something you need, I can implement it.
