### ISSUE TITLE
More Than One Browser Window Breaks Per-Site Proxy

### ISSUE THREAD

**Issue by tinyvoice** [mullvad/browser-extension#265]
I filed an issue about this problem in March (#198), and it was closed as completed/merged in April, but the problem has remained for me ever since despite the various releases and the new UI. The release notes for 0.9.1 show it as being fixed even though I still have the same problem in both Firefox and Mullvad Browser. What do I as the user need to do for the #212 fix to take effect?

Problem Summary:
Opening more than one browser window breaks the proxy for [domain.tld] feature. When you are in a new window, the domain name given for setting the per-site proxy will still be that of the focused tab in the first window. This means there is no way to set the per-site proxy for the website you are currently viewing in the second browser window. See #198 for screenshots of the problem in the old UI. (I have been unable to get a screenshot in the new UI without the extension window disappearing.)

**Comment by ruihildt** [comment]
Did some git archeology and this is a regression. In version 0.9.3, I reverted the fix while refactoring.

I will re-apply it in the coming version. Sorry for that.
