### ISSUE TITLE
Set the search engine to something else than Google/Bing

### ISSUE THREAD

**Issue by ruihildt** [mullvad/browser-extension#39]
It's arguably better to use DuckDuckGo, even if it doesn't provide better privacy in the browser by itself.

Maybe we could recommend using another search engine if users are using Google/Bing, etc.

Should be doable with: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides

**Comment by ph00lt0** [comment]
I don't see why this should be part of your add-on. Just keep it simple!!! Focus on what mullvad can do. You can always write a blog post on other recommendations for privacy friendly browser. Or direct users to websites like privacyguides.org. Who actively maintains good advice on it's website.

**Comment by Erghel** [comment]
**Swisscows**, **Lukol** and **MetaGer** better than Google/Bing too.

**Comment by Erghel** [comment]
> **Swisscows**, **Lukol**, **SearXNG** and **MetaGer** better than Google/Bing too.

You can also pay attention to the extension created by our team, which just touches on the issue of search engines: 

Mozilla addons release - https://addons.mozilla.org/ru/firefox/addon/answerius/
Our website - https://erghel.github.io/Answerius/

**Comment by ruihildt** [comment]
@ph00lt0 We don't have plans to recommend a specific search engine.

In a perfect world, it shouldn't matter what website you visit/use if your browser can't be fingerprinted.
