### ISSUE TITLE
Recommend disabling DoH when using mullvad

### ISSUE THREAD

**Issue by ruihildt** [mullvad/browser-extension#9]
There's no privacy benefits to use DoH when using Mullvad.
If a user has DoH set, we should recommend them to disable it.

Also, see #11

**Comment by PeterDaveHello** [comment]
I'm not sure. If we're using a trusted DoH resolver with enhanced features, I'd like to keep it that way.

**Comment by ruihildt** [comment]
@PeterDaveHello This would be a recommendation aimed at people who run a default DoH server while even not being aware of it. For example, Firefox has started to enable third party DoH by default in some countries.

There will always be a setting in the interface to ignore any recommendation that doesn't fit what you're trying to achieve.
